### ISSUE TITLE
www-plugins/chrome-token-signing-1.1.5-r1 fails 11 tests

### ISSUE THREAD

**Issue by jaakristioja** [open-eid/gentoo#58]
`[ebuild     U ~] www-plugins/chrome-token-signing-1.1.5-r1::esteid [1.1.5::esteid] USE="chrome firefox" 0 KiB`

```
>>> Test phase: www-plugins/chrome-token-signing-1.1.5-r1
make -j5   test
make `uname`
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[1]: Entering directory '/var/tmp/portage/www-plugins/chrome-token-signing-1.1.5-r1/work/chrome-token-signing-1.1.5'
make -C host-linux
make[2]: Entering directory '/var/tmp/portage/www-plugins/chrome-token-signing-1.1.5-r1/work/chrome-token-signing-1.1.5/host-linux'
make[2]: Nothing to be done for 'first'.
make[2]: Leaving directory '/var/tmp/portage/www-plugins/chrome-token-signing-1.1.5-r1/work/chrome-token-signing-1.1.5/host-linux'
make[1]: Leaving directory '/var/tmp/portage/www-plugins/chrome-token-signing-1.1.5-r1/work/chrome-token-signing-1.1.5'
# wildcard will resolve to an empty string with a missing file
# so that OSX will not run with xvfb
python host-test/pipe-test.py -v
test_empty_json (__main__.TestHostPipe.test_empty_json) ... 
Running native component on PID 32
SEND: {}
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: minimal, offscreen, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

ERROR
test_inconsistent_origin (__main__.TestHostPipe.test_inconsistent_origin) ... 
Running native component on PID 33
SEND: {"type": "VERSION", "nonce": "e3f3b605-d363-4ee5-afaa-a05ec0d2b29f", "origin": "http://example.com/"}
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: minimal, offscreen, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

ERROR
test_plain_string (__main__.TestHostPipe.test_plain_string) ... 
Running native component on PID 34
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: minimal, offscreen, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

ERROR
test_random_string (__main__.TestHostPipe.test_random_string) ... 
Running native component on PID 35
SEND: BLAH
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: minimal, offscreen, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

ERROR
test_utopic_length (__main__.TestHostPipe.test_utopic_length) ... 
Running native component on PID 36
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: minimal, offscreen, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

ERROR
test_version_file_origin (__main__.TestHostPipe.test_version_file_origin) ... 
Running native component on PID 37
SEND: {"type": "VERSION", "nonce": "e633caad-12e1-44a2-a355-0f4de7188e9c", "origin": "file:///tmp/index.html"}
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: minimal, offscreen, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

ERROR
test_version_http_origin (__main__.TestHostPipe.test_version_http_origin) ... 
Running native component on PID 38
SEND: {"type": "VERSION", "nonce": "2547022d-380b-4db4-8f8b-90c5861bdcbd", "origin": "http://example.com/"}
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: minimal, offscreen, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

ERROR
test_version_https (__main__.TestHostPipe.test_version_https) ... 
Running native component on PID 39
SEND: {"type": "VERSION", "nonce": "645f7ec7-b6ea-4fed-92c7-ec8bf7e1fb2a", "origin": "https://example.com/"}
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: minimal, offscreen, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

ERROR
test_version_invalid_origin (__main__.TestHostPipe.test_version_invalid_origin) ... 
Running native component on PID 40
SEND: {"type": "VERSION", "nonce": "e0ccc26a-45f8-4db1-bafa-b1d04a1a9c49", "origin": "foobar in da house"}
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: minimal, offscreen, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

ERROR
test_version_no_nonce (__main__.TestHostPipe.test_version_no_nonce) ... 
Running native component on PID 41
SEND: {"type": "VERSION", "origin": "https://example.com/"}
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: minimal, offscreen, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

ERROR
test_version_no_origin (__main__.TestHostPipe.test_version_no_origin) ... 
Running native component on PID 42
SEND: {"type": "VERSION", "nonce": "9ece7968-21d8-4837-904b-8d39a4cbaa84"}
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: minimal, offscreen, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

ERROR

======================================================================
ERROR: test_empty_json (__main__.TestHostPipe.test_empty_json)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/www-plugins/chrome-token-signing-1.1.5-r1/work/chrome-token-signing-1.1.5/host-test/pipe-test.py", line 78, in test_empty_json
    resp = self.transceive(json.dumps(cmd))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/www-plugins/chrome-token-signing-1.1.5-r1/work/chrome-token-signing-1.1.5/host-test/pipe-test.py", line 49, in transceive
    return self.get_response()
           ^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/www-plugins/chrome-token-signing-1.1.5-r1/work/chrome-token-signing-1.1.5/host-test/pipe-test.py", line 36, in get_response
    response_length = struct.unpack("=I", self.p.stdout.read(4))[0]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 4 bytes

======================================================================
ERROR: test_inconsistent_origin (__main__.TestHostPipe.test_inconsistent_origin)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/www-plugins/chrome-token-signing-1.1.5-r1/work/chrome-token-signing-1.1.5/host-test/pipe-test.py", line 101, in test_inconsistent_origin
    resp1 = self.transceive(json.dumps(cmd))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/www-plugins/chrome-token-signing-1.1.5-r1/work/chrome-token-signing-1.1.5/host-test/pipe-test.py", line 49, in transceive
    return self.get_response()
           ^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/www-plugins/chrome-token-signing-1.1.5-r1/work/chrome-token-signing-1.1.5/host-test/pipe-test.py", line 36, in get_response
    response_length = struct.unpack("=I", self.p.stdout.read(4))[0]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 4 bytes

======================================================================
ERROR: test_plain_string (__main__.TestHostPipe.test_plain_string)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/www-plugins/chrome-token-signing-1.1.5-r1/work/chrome-token-signing-1.1.5/host-test/pipe-test.py", line 72, in test_plain_string
    resp = self.get_response()
           ^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/www-plugins/chrome-token-signing-1.1.5-r1/work/chrome-token-signing-1.1.5/host-test/pipe-test.py", line 36, in get_response
    response_length = struct.unpack("=I", self.p.stdout.read(4))[0]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 4 bytes

======================================================================
ERROR: test_random_string (__main__.TestHostPipe.test_random_string)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/www-plugins/chrome-token-signing-1.1.5-r1/work/chrome-token-signing-1.1.5/host-test/pipe-test.py", line 66, in test_random_string
    resp = self.transceive(cmd)
           ^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/www-plugins/chrome-token-signing-1.1.5-r1/work/chrome-token-signing-1.1.5/host-test/pipe-test.py", line 49, in transceive
    return self.get_response()
           ^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/www-plugins/chrome-token-signing-1.1.5-r1/work/chrome-token-signing-1.1.5/host-test/pipe-test.py", line 36, in get_response
    response_length = struct.unpack("=I", self.p.stdout.read(4))[0]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 4 bytes

======================================================================
ERROR: test_utopic_length (__main__.TestHostPipe.test_utopic_length)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/www-plugins/chrome-token-signing-1.1.5-r1/work/chrome-token-signing-1.1.5/host-test/pipe-test.py", line 86, in test_utopic_length
    resp = self.get_response()
           ^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/www-plugins/chrome-token-signing-1.1.5-r1/work/chrome-token-signing-1.1.5/host-test/pipe-test.py", line 36, in get_response
    response_length = struct.unpack("=I", self.p.stdout.read(4))[0]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 4 bytes

======================================================================
ERROR: test_version_file_origin (__main__.TestHostPipe.test_version_file_origin)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/www-plugins/chrome-token-signing-1.1.5-r1/work/chrome-token-signing-1.1.5/host-test/pipe-test.py", line 125, in test_version_file_origin
    resp = self.transceive(json.dumps(cmd))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/www-plugins/chrome-token-signing-1.1.5-r1/work/chrome-token-signing-1.1.5/host-test/pipe-test.py", line 49, in transceive
    return self.get_response()
           ^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/www-plugins/chrome-token-signing-1.1.5-r1/work/chrome-token-signing-1.1.5/host-test/pipe-test.py", line 36, in get_response
    response_length = struct.unpack("=I", self.p.stdout.read(4))[0]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 4 bytes

======================================================================
ERROR: test_version_http_origin (__main__.TestHostPipe.test_version_http_origin)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/www-plugins/chrome-token-signing-1.1.5-r1/work/chrome-token-signing-1.1.5/host-test/pipe-test.py", line 131, in test_version_http_origin
    resp = self.transceive(json.dumps(cmd))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/www-plugins/chrome-token-signing-1.1.5-r1/work/chrome-token-signing-1.1.5/host-test/pipe-test.py", line 49, in transceive
    return self.get_response()
           ^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/www-plugins/chrome-token-signing-1.1.5-r1/work/chrome-token-signing-1.1.5/host-test/pipe-test.py", line 36, in get_response
    response_length = struct.unpack("=I", self.p.stdout.read(4))[0]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 4 bytes

======================================================================
ERROR: test_version_https (__main__.TestHostPipe.test_version_https)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/www-plugins/chrome-token-signing-1.1.5-r1/work/chrome-token-signing-1.1.5/host-test/pipe-test.py", line 137, in test_version_https
    resp = self.transceive(json.dumps(cmd))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/www-plugins/chrome-token-signing-1.1.5-r1/work/chrome-token-signing-1.1.5/host-test/pipe-test.py", line 49, in transceive
    return self.get_response()
           ^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/www-plugins/chrome-token-signing-1.1.5-r1/work/chrome-token-signing-1.1.5/host-test/pipe-test.py", line 36, in get_response
    response_length = struct.unpack("=I", self.p.stdout.read(4))[0]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 4 bytes

======================================================================
ERROR: test_version_invalid_origin (__main__.TestHostPipe.test_version_invalid_origin)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/www-plugins/chrome-token-signing-1.1.5-r1/work/chrome-token-signing-1.1.5/host-test/pipe-test.py", line 119, in test_version_invalid_origin
    resp = self.transceive(json.dumps(cmd))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/www-plugins/chrome-token-signing-1.1.5-r1/work/chrome-token-signing-1.1.5/host-test/pipe-test.py", line 49, in transceive
    return self.get_response()
           ^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/www-plugins/chrome-token-signing-1.1.5-r1/work/chrome-token-signing-1.1.5/host-test/pipe-test.py", line 36, in get_response
    response_length = struct.unpack("=I", self.p.stdout.read(4))[0]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 4 bytes

======================================================================
ERROR: test_version_no_nonce (__main__.TestHostPipe.test_version_no_nonce)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/www-plugins/chrome-token-signing-1.1.5-r1/work/chrome-token-signing-1.1.5/host-test/pipe-test.py", line 109, in test_version_no_nonce
    resp = self.transceive(json.dumps(cmd))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/www-plugins/chrome-token-signing-1.1.5-r1/work/chrome-token-signing-1.1.5/host-test/pipe-test.py", line 49, in transceive
    return self.get_response()
           ^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/www-plugins/chrome-token-signing-1.1.5-r1/work/chrome-token-signing-1.1.5/host-test/pipe-test.py", line 36, in get_response
    response_length = struct.unpack("=I", self.p.stdout.read(4))[0]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 4 bytes

======================================================================
ERROR: test_version_no_origin (__main__.TestHostPipe.test_version_no_origin)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/www-plugins/chrome-token-signing-1.1.5-r1/work/chrome-token-signing-1.1.5/host-test/pipe-test.py", line 114, in test_version_no_origin
    resp = self.transceive(json.dumps(cmd))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/www-plugins/chrome-token-signing-1.1.5-r1/work/chrome-token-signing-1.1.5/host-test/pipe-test.py", line 49, in transceive
    return self.get_response()
           ^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/www-plugins/chrome-token-signing-1.1.5-r1/work/chrome-token-signing-1.1.5/host-test/pipe-test.py", line 36, in get_response
    response_length = struct.unpack("=I", self.p.stdout.read(4))[0]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 4 bytes

----------------------------------------------------------------------
Ran 11 tests in 0.172s

FAILED (errors=11)
make: *** [GNUmakefile:42: test] Error 1
```

[build.log](https://github.com/open-eid/gentoo/files/10661923/build.log)

**Comment by metsma** [comment]
I think xvfb is needed for running tests.
https://github.com/open-eid/chrome-token-signing/blob/master/.github/workflows/build.yml#L35

Hine chrome-token-signing is deprecated, replacement https://github.com/web-eid/web-eid-app

**Comment by urmet** [comment]
yep, this should probably be removed instead of being fixed :)

**Comment by lkraav** [comment]
Closed in #65?
